# Generated by Django 3.1.7 on 2021-11-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('flag', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('target', models.IntegerField()),
            ],
        ),
    ]
