# Generated by Django 3.2.9 on 2021-11-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
